version: '3.4'

services:
#////////////////////////////////////////////////////////////////////////////// REDIS
  redis.master:
    container_name: "MeminToDo.Redis.Master"
    command: redis-server
    ports:
      - "8030:6379"
    networks:
      - MeminToDo.RedisNetwork

  redis.slave1:
    container_name: "MeminToDo.Redis.Slave1"
    ports:
      - "8031:6379"
    command: redis-server --slaveof redisMaster 6379
    networks:
      - MeminToDo.RedisNetwork

  redis.slave2:
    container_name: "MeminToDo.Redis.Slave2"
    ports:
      - "8032:6379"
    command: redis-server --slaveof redisMaster 6379
    networks:
      - MeminToDo.RedisNetwork

  redis.slave3:
    container_name: "MeminToDo.Redis.Slave2"
    ports:
      - "8033:6379"
    command: redis-server --slaveof redisMaster 6379
    networks:
      - MeminToDo.RedisNetwork

  redis.sentinel1:
    container_name: 'MeminToDo.Redis.Sentinel1'
    ports:
      - "8034:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "C:/Users/rock_/OneDrive/Belgeler/PROJELER2/memind/MeminToDo/src/BuildingBlocks/Common.Caching/Common.Caching/sentinel.conf:/usr/local/etc/redis/sentinel.conf"
    networks:
      - MeminToDo.RedisNetwork
      
  redis.sentinel2:
    container_name: 'MeminToDo.Redis.Sentinel2'
    ports:
      - "8035:26379"
    command: redis redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "C:/Users/rock_/OneDrive/Belgeler/PROJELER2/memind/MeminToDo/src/BuildingBlocks/Common.Caching/Common.Caching/sentinel.conf:/usr/local/etc/redis/sentinel.conf"
    networks:
      - MeminToDo.RedisNetwork
 


#////////////////////////////////////////////////////////////////////////////// GATEWAY
  ocelotapigateway:
    container_name: MeminToDo.Ocelot.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - workout.api
      - entertainment.api
      - skill.api
      - budget.api
      - meal.api
    ports:
      - "8020:80"
    networks:
      - MeminToDo.OcelotNetwork

#////////////////////////////////////////////////////////////////////////////// OUTER SERVICES
  portainer:
    container_name: MeminToDo.Portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  seq:
    container_name: MeminToDo.Seq
    environment:
        - ACCEPT_EULA=Y
    ports:
        - "8013:80"
    networks:
      - MeminToDo.SeqNetwork
      
  elasticsearch:
    container_name: MeminToDo.ElasticSearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "8012:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - MeminToDo.ElasticNetwork

  kibana:
    container_name: MeminToDo.Kibana
    environment:
      - ELASTICSEARCH_URL=http://memintodo.elasticsearch:8012
    depends_on:
      - elasticsearch
    ports:
      - "8011:5601" 
    networks:
      - MeminToDo.ElasticNetwork

  consul:
    container_name: MeminToDo.Consul
    restart: always
    hostname: "localhost"
    ports:
      - "8014:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    networks:
      - MeminToDo.ConsulNetwork
    command: ["consul", "agent", "-server", "-ui", "-bind", "0.0.0.0", "-client", "0.0.0.0", "-data-dir", "/consul/data", "-config-dir", "/consul/config", "-bootstrap", "-datacenter", "docker", ]
 
  jaeger:
    container_name: MeminToDo.Jaeger
    restart: always
    hostname: "localhost"
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14268:14268"
      - "14250:14250"
      - "8015:16686"
      - "5778:5778"
    networks:
      - MeminToDo.JaegerNetwork

  prometheus:
    container_name: MeminToDo.Prometheus
    ports:
      - "8016:9090"
    environment:
      - TZ=UTC+3
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: MeminToDo.Grafana
    ports:
      - "8017:3000"
    volumes:
      - ./grafana-data/data:/var/lib/grafana 
    depends_on:
      - prometheus

#////////////////////////////////////////////////////////////////////////////// PROJECT SERVICES
  workout.api:
    container_name: MeminToDo.Workout.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://memintodo.elasticsearch:8012"
      - "Seq:ServerUrl=http://MeminToDo.Seq:8013"
    ports:
      - "8001:80"
    networks:
      - MeminToDo.ConsulNetwork
      - MeminToDo.SeqNetwork
      - MeminToDo.OcelotNetwork
      - MeminToDo.ElasticNetwork
    depends_on:
      - kibana
      
  meal.api:
    container_name: MeminToDo.Meal.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:MsSqlDatabaseConnectionString=Server=MONSTER; Database=MealDB; Trusted_Connection=True; Encrypt=False;"
      - "ElasticConfiguration:Uri=http://memintodo.elasticsearch:8012"
      - "Seq:ServerUrl=http://MeminToDo.Seq:8013"
    ports:
      - "8006:80"
    networks:
      - MeminToDo.ConsulNetwork
      - MeminToDo.SeqNetwork
      - MeminToDo.OcelotNetwork
      - MeminToDo.ElasticNetwork
    depends_on:
      - kibana

  skill.api:
    container_name: MeminToDo.Skill.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development   
      - MongoConnection:ConnectionString=
      - MongoConnection:Database=
      - "ElasticConfiguration:Uri=http://memintodo.elasticsearch:8012"
      - "Seq:ServerUrl=http://memintodo.seq:8013"
      - "S3:AccessKey="
      - "S3:SecretKey="
      - "S3:BucketName="
      - "Blob:StorageAccount="
      - "Blob:Key="
      - "Blob:BlobContainerName="
      - "Blob:BlobUri="
    ports:
      - "8002:80"
    networks:
      - MeminToDo.ConsulNetwork
      - MeminToDo.SeqNetwork
      - MeminToDo.OcelotNetwork
      - MeminToDo.ElasticNetwork
    depends_on:
      - kibana

  entertainment.api:
    container_name: MeminToDo.Entertainment.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - PostgreSql=
      - "ElasticConfiguration:Uri=http://memintodo.elasticsearch:8012"
      - "Seq:ServerUrl=http://memintodo.seq:8013"
    ports:
      - "8003:80"
    networks:
      - MeminToDo.ConsulNetwork
      - MeminToDo.SeqNetwork
      - MeminToDo.OcelotNetwork
      - MeminToDo.ElasticNetwork
    depends_on:
      - kibana

  budget.api:
    container_name: MeminToDo.Budget.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:MsSqlDatabaseConnectionString=Server="
      - "ElasticConfiguration:Uri=http://memintodo.elasticsearch:8012"
      - "Seq:ServerUrl=http://memintodo.seq:8013"
    ports:
      - "8008:80"
    networks:
      - MeminToDo.ConsulNetwork
      - MeminToDo.SeqNetwork
      - MeminToDo.OcelotNetwork
      - MeminToDo.ElasticNetwork
    depends_on:
      - kibana
      
  dashboard.aggregator:
    container_name: MeminToDo.Dashboard.Aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:WorkoutUrl=http://memintodo.workout.api"
      - "ApiSettings:EntertainmentUrl=http://memintodo.entertainment.api"
      - "ApiSettings:SkillUrl=http://memintodo.skill.api"
      - "ElasticConfiguration:Uri=http://memintodo.elasticsearch:8012"
      - "Seq:ServerUrl=http://memintodo.seq:8013"
    ports:
      - "8004:80"
    networks:
      - MeminToDo.ConsulNetwork
      - MeminToDo.SeqNetwork
      - MeminToDo.OcelotNetwork
      - MeminToDo.ElasticNetwork
    depends_on:
      - kibana

  healthcheck:
    container_name: MeminToDo.HealthCheck
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Workout API Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://memintodo.workout.api/hc
      - HealthChecksUI__HealthChecks__1__Name=Skill API Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://memintodo.skill.api/hc
      - HealthChecksUI__HealthChecks__2__Name=Entertainment API Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://memintodo.entertainment.api/hc
      - HealthChecksUI__HealthChecks__3__Name=Dashboard Service Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://memintodo.dashboard.aggregator/hc
      - HealthChecksUI__HealthChecks__4__Name=Meal Service Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://memintodo.meal.api/hc
      - HealthChecksUI__HealthChecks__5__Name=Budget Service Health Check
      - HealthChecksUI__HealthChecks__5__Uri=http://memintodo.budget.api/hc
      - WorkoutService__Url=http://memintodo.workout.api
      - WorkoutService__ServiceName=Workout Service
      - WorkoutService__ServiceId=Workout
      - MealService__Url=http://memintodo.meal.api
      - MealService__ServiceName=Meal Service
      - MealService__ServiceId=Meal
      - SkillService__Url=http://memintodo.skill.api
      - SkillService__ServiceName=Skill Service
      - SkillService__ServiceId=Skill
      - EntertainmentService__Url=http://memintodo.entertainment.api
      - EntertainmentService__ServiceName=Entertainment Service
      - EntertainmentService__ServiceId=Entertainment
      - DashboardAggregator__Url=http://memintodo.dashboard.aggregator
      - DashboardAggregator__ServiceName=Dashboard Service
      - DashboardAggregator__ServiceId=Dashboard
      - BudgetService__Url=http://memintodo.budget.api
      - BudgetService__ServiceName=Budget Service
      - BudgetService__ServiceId=Budget
      - Consul__Host=http://192.168.80.2:8014
    ports:
      - "8010:80"
    depends_on:
      - consul
      - grafana
      - kibana
      - prometheus
      - jaeger
      - entertainment.api
      - dashboard.aggregator
      - skill.api
      - workout.api
      - meal.api
    networks:
      - MeminToDo.ConsulNetwork
  
  #user.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #  ports:
  #    - "80"
  #    - "443"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  log.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AWS:Profile="
      - "AWS:Region="
    ports:
      - "8007:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  portainer_data:
  elasticsearch-data:

networks:
  MeminToDo.SeqNetwork:
    driver: bridge
  MeminToDo.JaegerNetwork:
    driver: bridge
  MeminToDo.ConsulNetwork:
    driver: bridge
  MeminToDo.ElasticNetwork:
    driver: bridge
  MeminToDo.OcelotNetwork:
    driver: bridge
  MeminToDo.RedisNetwork:
    driver: bridge



