namespace Common.Logging.Helpers
{
    internal static class LogPatterns
    {
        internal static string[] GetLogPatterns()
        {
            return new string[]
            {
                "An error occured:",
                "Created Show:",
                "Deleted Show:",
                "Getting All Shows",
                "Getting Show:",
                "Getting All Shows Of User:",
                "Updated Show:",
                "Created Game:",
                "Deleted Game:",
                "Getting All Games",
                "Getting Game:",
                "Getting All Games Of User:",
                "Updated Game:",
                "Created Book:",
                "Deleted Book:",
                "Getting All Books",
                "Getting Book:",
                "Getting All Books Of User:",
                "Updated Book:",
                "Created Book Note:",
                "Deleted Book Note:",
                "Getting All Book Notes",
                "Getting Book Note:",
                "Getting All Book Notes Of User:",
                "Updated Book Note:",


                "Created Budget Account:",
                "Deleted Budget Account Successfully:",
                "Getting All Budget Accounts Successfully.",
                "Getting Budget Account With Tracking:",
                "Getting All Budget Accounts Of User",
                "Updated Budget Account Successfully:",
                "Created Money Flow:",
                "Deleted Money Flow Successfully:",
                "Getting All Money Flows Successfully.",
                "Getting Money Flow With Tracking:",
                "Getting Money Flow Without Tracking:",
                "Getting All Money Flows Of User",
                "Updated Money Flow Successfully:",
                "Created Wallet:",
                "Deleted Wallet Successfully:",
                "Getting All Wallets Successfully.",
                "Getting Wallet With Tracking:",
                "Getting Wallet Without Tracking:",
                "Getting All Wallets Of User",
                "Updated Wallet Successfully:",


                "Created Food:",
                "Getting All Active Foods Successfully.",
                "Getting All Deleted Foods Successfully.",
                "Getting All Foods Successfully.",
                "Getting All Foods In Meal:",
                "Getting All Food History Successfully.",
                "Getting Food:",
                "Getting Food History:",
                "Getting Food History From",
                "Getting All Foods Of User",
                "Hard Deleted Food Successfully:",
                "Soft Deleted Food Successfully:",
                "Updated Food Successfully:",
                "Created Meal Successfully.",
                "Getting All Active Meals Successfully.",
                "Getting All Deleted Meals Successfully.",
                "Getting All Meals Successfully.",
                "Getting All Meals In Meal:",
                "Getting All Meal History Successfully.",
                "Getting Meal:",
                "Getting Meal History:",
                "Getting Meal History From",
                "Getting All Meals Of User",
                "Hard Deleted Meal Successfully:",
                "Soft Deleted Meal Successfully:",
                "Updated Meal Successfully:",


                "Created Song:",
                "Deleted Song:",
                "Getting All Songs",
                "Getting All Songs Of User:",
                "Getting Song:",
                "Updated Song:",
                "Created Art:",
                "Deleted Art:",
                "Getting All Arts",
                "Getting All Arts Of User:",
                "Getting Art:",
                "Updated Art:",


                "Created Exercise:",
                "Deleted Exercise:",
                "Getting All Exercises",
                "Getting All Exercises In Workout:",
                "Getting Exercise:",
                "Getting Users All Exercises:",
                "Updated Exercise:",
                "Created Workout:",
                "Deleted Workout:",
                "Getting All Workouts",
                "Getting Workout:",
                "Getting Users All Workouts:",
                "Updated Workout:"
            };
        }
    }
}
