global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []
scrape_configs:
- job_name: WorkoutAPITracking
  honor_timestamps: true
  scrape_interval: 15s  
  scrape_timeout: 10s  
  metrics_path: /metrics-text 
  scheme: http
  static_configs:  
  - targets:  
    - "host.docker.internal:8001"

- job_name: SkillAPITrack
  honor_timestamps: true
  scrape_interval: 15s  
  scrape_timeout: 10s  
  metrics_path: /metrics-text 
  scheme: http
  static_configs:  
  - targets:  
    - "host.docker.internal:8002"

- job_name: EntertainmentAPITrack
  honor_timestamps: true
  scrape_interval: 15s  
  scrape_timeout: 10s  
  metrics_path: /metrics-text 
  scheme: http
  static_configs:  
  - targets:  
    - "host.docker.internal:8003"